spring:
 datasource:
  url: jdbc:mysql://one-two-estudo.coy5hev8tysf.us-east-2.rds.amazonaws.com/onetwoestudo
  username: admin
  password: admin1234
 jpa:
   hibernate:
      ddl-auto: update
   show-sql: true
 security:
   oauth2:
     resourceserver:
       opaquetoken:
         introspection-uri: http://127.0.0.1:8082/oauth2/introspect
         client-id: onetwo-backend
         client-secret: backend123
         
server:
 port: 8082
 

api:
 auth:
  providerUrl: http://localhost:8082
 security:
   token:
     secret: ${JWT_SECRET:my-secret-key}