spring:
 servlet:
    multipart:
      max-file-size: 100MB      
      max-request-size: 100MB  
 datasource:
  url: jdbc:mysql://one-two.c5kps9ts3u0h.us-east-1.rds.amazonaws.com/onetwo
  username: admin
  password: admin123
 jpa:
   hibernate:
      ddl-auto: update
   show-sql: true
 security:
   oauth2:
     resourceserver:
       opaquetoken:
         introspection-uri: http://127.0.0.1:8082/oauth2/introspect
         client-id: onetwo-backend
         client-secret: backend123
         
server:
 port: 8082
 
api:
 auth:
  providerUrl: http://localhost:8082
 security:
   token:
     secret: ${JWT_SECRET:my-secret-key}
     
onetwo-storage:
    local: 
     diretorio: /Users/lucas/Desktop/arquivos-tcc
    s3: 
      id-chave-acesso: AKIA3UTCRJWVFY2NB46T
      id-chave-acesso-secreta: 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
      bucket: onetwo-arquivos-estudo
      regiao: us-east-2
      diretorio: catalogo
      